enableVersioning: true
handle: portfolioHome
name: 'Portfolio Home'
propagationMethod: all
siteSettings:
  a04326fe-2cd3-42e2-8ca0-2d7eef73c65e:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
